#!/bin/bash

USERNAME=$(whoami)
CURRENT_DIR=$(pwd)
SCRIPT_FILE="$CURRENT_DIR/goes"
SERVICE_TEMPLATE="goes.service"
SERVICE_FILE="$HOME/.config/systemd/user/goes.service"

chmod +x "$SCRIPT_FILE"
mkdir -p "$HOME/.config/systemd/user/"
cp "$SERVICE_TEMPLATE" "$SERVICE_FILE"

# Note: Satellite selection is now handled by install.sh

# Replace placeholders
sed "s#\$SCRIPT#${SCRIPT_FILE}#g" -i "$SERVICE_FILE"
sed "s#\$USERNAME#${USERNAME}#g" -i "$SERVICE_FILE"

# Start service
systemctl --user daemon-reload
systemctl --user stop goes.service
systemctl --user enable goes.service
systemctl --user start goes.service
systemctl --user status goes.service

echo "Service installed and started successfully."
echo ""
echo "To manage the service, use the following commands:"
echo "  goes start   - Start the wallpaper service"
echo "  goes stop    - Stop the wallpaper service"
echo "  goes enable  - Enable the wallpaper service to start at login"
echo "  goes disable - Disable the wallpaper service from starting at login"
echo "  goes status  - Check if the wallpaper service is running"